name: CD - Deploy API Inference

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ”‘ Autenticarse en GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: ğŸ”§ Configurar gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: mlops-latam

      - name: ğŸ³ Construir y subir imagen a Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/mlops-latam/mlopsengel/api-inference-deploy:latest challenge/api/
          docker push us-central1-docker.pkg.dev/mlops-latam/mlopsengel/api-inference-deploy:latest

      - name: ğŸš€ Desplegar en Cloud Run con 8GB RAM
        run: |
          gcloud run deploy api-inference-deploy \
            --image us-central1-docker.pkg.dev/mlops-latam/mlopsengel/api-inference-deploy:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --memory=8Gi \
            --cpu=2 \
            --port=8080 \
            --service-account=ci-cd-deploy@mlops-latam.iam.gserviceaccount.com
